apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to Nginx</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          margin: 0;
          background-color: #f4f4f9;
          color: #333;
        }
        .container {
          text-align: center;
          max-width: 600px;
          padding: 2rem;
          background-color: #fff;
          box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
          border-radius: 8px;
        }
        h1 {
          color: #007bff;
          font-size: 2.5rem;
          margin: 0;
        }
        p {
          font-size: 1.1rem;
          line-height: 1.6;
          color: #555;
        }
        .button {
          display: inline-block;
          padding: 0.8rem 1.5rem;
          margin-top: 1.5rem;
          font-size: 1rem;
          color: #fff;
          background-color: #007bff;
          text-decoration: none;
          border-radius: 5px;
          transition: background-color 0.3s;
        }
        .button:hover {
          background-color: #0056b3;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Welcome to Nginx</h1>
        <p>Congratulations! Your Nginx server is up and running.</p>
        <p>This is a simple static page served by Nginx.</p>
        <a href="https://nginx.org" target="_blank" class="button">Learn more about Nginx</a>
      </div>
    </body>
    </html>
