apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx_values.service.name }}
spec:
  selector:
    app: {{ .Values.nginx_values.service.app }}
  ports:
  {{- with .Values.nginx_values.service }}
  - protocol: {{ .ports.protocol }}
    port: {{ .ports.port }}
    targetPort: {{ .ports.targetPort }}
  type: {{ .ports.type }}
  {{- end }}